services:
  nginx:
    image: nginx:latest
    container_name: jewelry-receipt-nginx
    ports:
      - "8097:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    restart: unless-stopped
  api:
    build:
      context: ./app
    image: jewelry-receipt-api:1.0
    container_name: jewelry-receipt-api
    environment:
      ONE_C_EXPORT_PATH: /data/receipts.csv
    volumes:
      - ./one-c-mock/receipts.csv:/data/receipts.csv:ro
    ports:
      - "8002:8000"
    restart: unless-stopped

  worker:
    build:
      context: ./worker
    image: jewelry-receipt-worker:1.0
    container_name: jewelry-receipt-worker
    environment:
      ONE_C_EXPORT_PATH: /data/receipts.csv
      SYNC_INTERVAL_SECONDS: "10"
    volumes:
      - ./one-c-mock/receipts.csv:/data/receipts.csv:ro
    depends_on:
      - api
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: jewelry-receipt-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api
    restart: unless-stopped
  grafana:
      image: grafana/grafana:latest
      container_name: jewelry-receipt-grafana
      ports:
        - "3001:3000"
      environment:
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
      depends_on:
        - prometheus
      restart: unless-stopped
